version: "3.9"
services:
    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
        environment:
            TZ: Asia/Bangkok
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        ports:
            - "9090:9090"
        environment:
            TZ: Asia/Bangkok
    grafana:
        container_name: grafana
        image: grafana/grafana-enterprise:8.2.0
        ports:
            - "9999:3000"
        environment:
            TZ: Asia/Bangkok